# Generated by Django 5.1.1 on 2024-10-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_in_school', models.CharField(choices=[('jr', 'Junior'), ('sr', 'Senior'), ('gr', 'Graduate')], max_length=2)),
            ],
            options={
                'verbose_name': 'student details',
                'ordering': ['roll_no'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.FloatField()),
                ('maths', models.FloatField()),
                ('chemistry', models.FloatField()),
                ('published_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrmApp.students')),
            ],
        ),
    ]
