# Generated by Django 5.1.1 on 2024-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0002_students_created_at_students_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.FileField(blank=True, help_text='Student ID card image', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
