# Generated by Django 5.1.1 on 2024-10-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0003_alter_students_created_at_alter_students_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_starting_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrmApp.students')),
            ],
        ),
    ]
