# Generated by Django 5.1.1 on 2024-10-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0004_students_details_alter_students_roll_no_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='OrmApp.students'),
        ),
    ]
